In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
df=pd.read_csv('Dataset of Diabetes .csv')
df.head()

ID  No_Pation Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0  502      17975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
1  735      34221      M   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6   
2  420      47975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
3  680      87656      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
4  504      34223      M   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4   

    BMI CLASS  
0  24.0     N  
1  23.0     N  
2  24.0     N  
3  24.0     N  
4  21.0     N

In [9]:
df.replace(to_replace ="P",
                 value ="1", inplace= True)
df.replace(to_replace ="Y",
                 value ="1", inplace= True)
df.replace(to_replace ="N",
                 value ="0", inplace= True)
df.replace(to_replace ="M",
                 value ="0", inplace= True)
df.replace(to_replace ="F",
                 value ="1", inplace= True)
df

ID  No_Pation Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0    502      17975      1   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
1    735      34221      0   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6   
2    420      47975      1   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
3    680      87656      1   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
4    504      34223      0   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4   
..   ...        ...    ...  ...   ...  ..    ...   ...  ...  ...  ...   ...   
494  397      47514      0   55   2.7  39   11.7   3.9  0.6  1.3  2.3   0.2   
495  681      34401      1   58   4.5  53    9.0   5.5  3.2  3.2  1.4   1.5   
496  749      34402      0   55   4.1  86   10.0   4.9  0.7  1.2  3.4   0.4   
497  321      34403      1   54   2.5  35   10.7   5.6  3.0  1.1  4.2   1.4   
498  381      32336      0   58   5.9  61    8.0   4.3  2.4  0.9  2.0   1.1   

      BMI CLASS  
0    24.0     0  
1    23.0     0  
2    24.0     0  
3    24.0     0  
4    21.0     0  
..    ...   ...  
494  30.0     1  
495  35.0     1  
496  33.0     1  
497  39.0     1  
498  29.0     1  

[499 rows x 14 columns]

In [10]:
new_data= df.drop('CLASS', axis=1)
df_feat=pd.DataFrame(new_data, columns= df.columns[:-1])
df.columns[:-1]

Index(['ID', 'No_Pation', 'Gender', 'AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG',
       'HDL', 'LDL', 'VLDL', 'BMI'],
      dtype='object')

In [4]:
df

ID  No_Pation Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0    502      17975      1   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
1    735      34221      0   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6   
2    420      47975      1   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
3    680      87656      1   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
4    504      34223      0   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4   
..   ...        ...    ...  ...   ...  ..    ...   ...  ...  ...  ...   ...   
494  397      47514      0   55   2.7  39   11.7   3.9  0.6  1.3  2.3   0.2   
495  681      34401      1   58   4.5  53    9.0   5.5  3.2  3.2  1.4   1.5   
496  749      34402      0   55   4.1  86   10.0   4.9  0.7  1.2  3.4   0.4   
497  321      34403      1   54   2.5  35   10.7   5.6  3.0  1.1  4.2   1.4   
498  381      32336      0   58   5.9  61    8.0   4.3  2.4  0.9  2.0   1.1   

      BMI CLASS  
0    24.0     0  
1    23.0     0  
2    24.0     0  
3    24.0     0  
4    21.0     0  
..    ...   ...  
494  30.0     1  
495  35.0     1  
496  33.0     1  
497  39.0     1  
498  29.0     1  

[499 rows x 14 columns]

In [12]:
from sklearn.model_selection import train_test_split
X= df_feat
y=df['CLASS']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=101)
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB()
gnb.fit(X_train,y_train)
pred=gnb.predict(X_test)
print(pred)

['0' '0' '0' 'N ' '0' 'N ' '0' '1' '0' '0' '0' '0' '0' '0' '0' '0' 'N '
 '0' 'N ' '0' '0' 'N ' '0' '0' '1' '0' '0' '0' '0' '0' '0' 'N ' '0' '0'
 'N ' '0' '0' '0' '0' '0' '1' 'N ' '0' '0' '0' '0' '0' 'N ' '0' '0' '0'
 '0' '1' 'N ' '0' '0' '0' '0' 'N ' '1' '0' '0' 'N ' '0' '0' '0' '0' '0'
 '0' '0' '0' '0' '0' '0' '0' 'N ' 'N ' '0' '0' '0' '0' '0' '0' '0' '0' '0'
 '0' '0' '0' '0' 'N ' '0' '0' '0' '0' '1' '0' '0' '0' '0' 'N ' '0' '0'
 'N ' '0' '0' 'N ' '0' '0' '0' '0' '0' 'N ' '0' '0' '0' '0' '0' '0' '0'
 '0' '0' '0' 'N ' '0' '1' '0' '0' '0' '0' 'N ' '0' '0' '0' '0' '0' 'N '
 '0' '0' '0' '0' '0' 'N ' '0' '0' '0' '0' '0' '0' '0']


In [7]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[21  4  7]
 [99  3 16]
 [ 0  0  0]]
              precision    recall  f1-score   support

           0       0.17      0.66      0.28        32
           1       0.43      0.03      0.05       118
          N        0.00      0.00      0.00         0

    accuracy                           0.16       150
   macro avg       0.20      0.23      0.11       150
weighted avg       0.37      0.16      0.10       150



C:\Users\Arpita Santra\New folder\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Arpita Santra\New folder\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Arpita Santra\New folder\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
